#
# Makefile for Phoenix-RTOS lowmemd (low memory monitor)
#
# Copyright 2026 Phoenix Systems
#
# %LICENSE%
#

NAME := lowmemd
LOCAL_PATH = $(call my-dir)
SRCS := $(wildcard $(LOCAL_PATH)*.c)
LOCAL_INSTALL_PATH := /bin

include $(binary.mk)
