#
# Makefile for Phoenix-RTOS prof (system-wide profiler: samples, waits, message edges)
#
# Copyright 2026 Phoenix Systems
#
# %LICENSE%
#

NAME := prof
LOCAL_PATH = $(call my-dir)
LOCAL_SRCS := prof.c record.c report.c event.c
LOCAL_INSTALL_PATH := /bin

include $(binary.mk)
